# How often should the plugin update the storage file and check if somebody levelled up?
updatePeriod: 120

# Should we ignore player with gamemode 1?
ignoreCreative: false

# Point numbers
points:

    # How many points do we get for an hour online time?
    time: 100
    # How many points do we get for one placed block?
    placed-block: 0.125
    # How many points do we get for one destroyed block?
    broken-block: 0.0625
    # How many points do we get for one killed monster?
    killed-monster: 2
    # How many points do we got for one killed animal?
    killed-animal: 0.1

# Messages
messages:

    # Shall we tell the whole server that somebody levels up?
    global-notify: true
    # Shall we display the help in the german language?
    german: false
    # Message to broadcast, when messages.global-notify is true
    # Variables: %player% (player name of the guy levelling up), %level% (name of the reached level)
    global-message: "%player% has just reached %level%."
    # Message to send to just the player
    # Variables: %level% (name of the reached level)
    message: "You've just reached %level%!"
    
    commands:
      status:
        name: "&7-- &6Level Status of $player &7--"
        current: "  &7Current level: &6 $currentlevelname &7($points points)"
        next: "  &7Next level: &6 $nextlevelname &7($neededpoints points)"
        nonext: "  &7Next level: &6None. You've reached the maximum."
        points: "  &7Activity points: &6 $points"
        time: "&7Online time: &6 $time"
        placed: "  &7Placed blocks: &6 $placed"
        broken: "  &7Broken blocks: &6 $broken" 
        unknown: "  This User is unknown to my level database"
    nopermission: "  You dont have the required permissions"
# Levels
levels:

    # This must be the name of your permissions group
    lvl1:
        # How should this level be called in the messages?
        name: Level 1
        # How many points does one need to reach this level?
        points: 0
    lvl2:
        name: Level 2
        points: 20

# Per world settings
worlds:

    # World's name here
    creative:

        # Ignore this world for levelling
        ignore: true
