name: Levelled
version: 1.0_Minecraft_1.7.2
description: Simple level plugin using online time, placed blocks and/or destroyed blocks (or any combinations) for levelling up.

author: ozzy2345

main: me.ozzyfant.levelled.Levelled
database: false
depend:
    - Vault

commands:
    level:
        description: Levelled main command
        aliases:
            - levelled
            - lvl
        usage: /<command>

permissions:
    levelled.*:
        description: Gives access to all Levelled commands.
        children:
            levelled.level: true
            levelled.status: true
            levelled.status.others: true
    levelled.level:
        description: Allows you to level up.
        default: true
    levelled.status:
        description: Allows you to see your status.
        default: true
    levelled.status.others:
        description: Allows you to see the status of other players.
        default: true