name: Levelled
version: 0.1
description: Simple level plugin using online time, placed blocks and/or destroyed blocks (or any combinations) for levelling up.

author: ozzy2345

main: me.ozzyfant.levelled.Levelled
database: false
#depend:
#    - Vault