name: Levelled
version: 0.1
description: Simple level plugin using online time, placed blocks and/or destroyed blocks (or any combinations) for levelling up.

author: ozzy2345

main: me.ozzyfant.levelled.Levelled
database: false
depend:
    - Vault

commands:
    level:
        description: Levelled main command
        aliases:
            - levelled
            - lvl
        permission: levelled.level
        usage: /<command>

permissions:
    levelled.*:
        description: Gives access to all Levelled commands.
        children:
            levelled.level: true
    levelled.level:
        description: Allows you to level up and view your status.
        default: true